### ISSUE TITLE
myLeviton API call (/Person/login) failed: 502

### ISSUE THREAD

**Issue by thinksilicon** [tlyakhov/python-decora_wifi#9]
Hi,
a few months ago I tested this project and it was working just fine. I took a break and now got back to it and I'm receiving a `502 Bad Gateway`-error now, whenever I try to run a command:

```
Traceback (most recent call last):
  File "dacora-cli2.py", line 11, in <module>
    session.login( "my@email.address", "mypassword" )
  File "/home/pi/.local/lib/python3.5/site-packages/decora_wifi/__init__.py", line 76, in login
    login_json = Person.login(self, payload)
  File "/home/pi/.local/lib/python3.5/site-packages/decora_wifi/models/person.py", line 569, in login
    return session.call_api(api, attribs, 'post')
  File "/home/pi/.local/lib/python3.5/site-packages/decora_wifi/__init__.py", line 53, in call_api
    self.login(self._email, self._password)
  File "/home/pi/.local/lib/python3.5/site-packages/decora_wifi/__init__.py", line 76, in login
    login_json = Person.login(self, payload)
  File "/home/pi/.local/lib/python3.5/site-packages/decora_wifi/models/person.py", line 569, in login
    return session.call_api(api, attribs, 'post')
  File "/home/pi/.local/lib/python3.5/site-packages/decora_wifi/__init__.py", line 60, in call_api
    raise ValueError(msg)
ValueError: myLeviton API call (/Person/login) failed: 502, <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>```

Did anything change in the api-address maybe? Or is there really an outage going on? (The App on the phone works fine though).

**Comment by tlyakhov** [comment]
Apologies, haven't had time to look at this. No longer using my Leviton integration so I can't verify quickly. I'll check this week.

**Comment by thinksilicon** [comment]
Hey, thanks for getting back on me. I don't know if that was the actual reason, but trying to figure out the problem I reset my password. Looks like that helped.
I'm still not entirely sure if it was just a service interruption or if changing the password helped.

Anyways, it's back working again. Thanks a lot!
